name: Test issues
on:
  issues:
    types: [opened,edited]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
      - uses: actions/checkout@v2
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Opening a PR for this...'
            })
            const script = require('something.js')
            await script({github, context, core})
